version: "3.8"

services:
  api:
    build: .
    ports:
      - "8001:8001"
      - PORT=8001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - .:/app
    restart: unless-stopped
